# coding: utf-8

"""
    SevOne API Documentation

    Supported endpoints by the new RESTful API  # noqa: E501

    OpenAPI spec version: 2.1.18, Hash: db562e6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.alert_flow_falcon_dto import AlertFlowFalconDto  # noqa: F401,E501


class AlertCreateDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alert_flow_falcon': 'AlertFlowFalconDto',
        'device_id': 'int',
        'end_time': 'int',
        'id': 'int',
        'ignore_comment': 'str',
        'ignore_uid': 'int',
        'ignore_until': 'int',
        'message': 'str',
        'number': 'int',
        'object_id': 'int',
        'origin': 'str',
        'plugin_name': 'str',
        'poll_id': 'int',
        'severity': 'int',
        'start_time': 'int'
    }

    attribute_map = {
        'alert_flow_falcon': 'alertFlowFalcon',
        'device_id': 'deviceId',
        'end_time': 'endTime',
        'id': 'id',
        'ignore_comment': 'ignoreComment',
        'ignore_uid': 'ignoreUid',
        'ignore_until': 'ignoreUntil',
        'message': 'message',
        'number': 'number',
        'object_id': 'objectId',
        'origin': 'origin',
        'plugin_name': 'pluginName',
        'poll_id': 'pollId',
        'severity': 'severity',
        'start_time': 'startTime'
    }

    def __init__(self, alert_flow_falcon=None, device_id=None, end_time=None, id=None, ignore_comment=None, ignore_uid=None, ignore_until=None, message=None, number=None, object_id=None, origin=None, plugin_name=None, poll_id=None, severity=None, start_time=None):  # noqa: E501
        """AlertCreateDto - a model defined in Swagger"""  # noqa: E501

        self._alert_flow_falcon = None
        self._device_id = None
        self._end_time = None
        self._id = None
        self._ignore_comment = None
        self._ignore_uid = None
        self._ignore_until = None
        self._message = None
        self._number = None
        self._object_id = None
        self._origin = None
        self._plugin_name = None
        self._poll_id = None
        self._severity = None
        self._start_time = None
        self.discriminator = None

        if alert_flow_falcon is not None:
            self.alert_flow_falcon = alert_flow_falcon
        if device_id is not None:
            self.device_id = device_id
        if end_time is not None:
            self.end_time = end_time
        if id is not None:
            self.id = id
        if ignore_comment is not None:
            self.ignore_comment = ignore_comment
        if ignore_uid is not None:
            self.ignore_uid = ignore_uid
        if ignore_until is not None:
            self.ignore_until = ignore_until
        if message is not None:
            self.message = message
        if number is not None:
            self.number = number
        if object_id is not None:
            self.object_id = object_id
        if origin is not None:
            self.origin = origin
        if plugin_name is not None:
            self.plugin_name = plugin_name
        if poll_id is not None:
            self.poll_id = poll_id
        if severity is not None:
            self.severity = severity
        if start_time is not None:
            self.start_time = start_time

    @property
    def alert_flow_falcon(self):
        """Gets the alert_flow_falcon of this AlertCreateDto.  # noqa: E501


        :return: The alert_flow_falcon of this AlertCreateDto.  # noqa: E501
        :rtype: AlertFlowFalconDto
        """
        return self._alert_flow_falcon

    @alert_flow_falcon.setter
    def alert_flow_falcon(self, alert_flow_falcon):
        """Sets the alert_flow_falcon of this AlertCreateDto.


        :param alert_flow_falcon: The alert_flow_falcon of this AlertCreateDto.  # noqa: E501
        :type: AlertFlowFalconDto
        """

        self._alert_flow_falcon = alert_flow_falcon

    @property
    def device_id(self):
        """Gets the device_id of this AlertCreateDto.  # noqa: E501


        :return: The device_id of this AlertCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """Sets the device_id of this AlertCreateDto.


        :param device_id: The device_id of this AlertCreateDto.  # noqa: E501
        :type: int
        """

        self._device_id = device_id

    @property
    def end_time(self):
        """Gets the end_time of this AlertCreateDto.  # noqa: E501

        Unix timestamp with milliseconds proximity  # noqa: E501

        :return: The end_time of this AlertCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this AlertCreateDto.

        Unix timestamp with milliseconds proximity  # noqa: E501

        :param end_time: The end_time of this AlertCreateDto.  # noqa: E501
        :type: int
        """

        self._end_time = end_time

    @property
    def id(self):
        """Gets the id of this AlertCreateDto.  # noqa: E501


        :return: The id of this AlertCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AlertCreateDto.


        :param id: The id of this AlertCreateDto.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def ignore_comment(self):
        """Gets the ignore_comment of this AlertCreateDto.  # noqa: E501


        :return: The ignore_comment of this AlertCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._ignore_comment

    @ignore_comment.setter
    def ignore_comment(self, ignore_comment):
        """Sets the ignore_comment of this AlertCreateDto.


        :param ignore_comment: The ignore_comment of this AlertCreateDto.  # noqa: E501
        :type: str
        """

        self._ignore_comment = ignore_comment

    @property
    def ignore_uid(self):
        """Gets the ignore_uid of this AlertCreateDto.  # noqa: E501


        :return: The ignore_uid of this AlertCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._ignore_uid

    @ignore_uid.setter
    def ignore_uid(self, ignore_uid):
        """Sets the ignore_uid of this AlertCreateDto.


        :param ignore_uid: The ignore_uid of this AlertCreateDto.  # noqa: E501
        :type: int
        """

        self._ignore_uid = ignore_uid

    @property
    def ignore_until(self):
        """Gets the ignore_until of this AlertCreateDto.  # noqa: E501

        Unix timestamp with milliseconds proximity  # noqa: E501

        :return: The ignore_until of this AlertCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._ignore_until

    @ignore_until.setter
    def ignore_until(self, ignore_until):
        """Sets the ignore_until of this AlertCreateDto.

        Unix timestamp with milliseconds proximity  # noqa: E501

        :param ignore_until: The ignore_until of this AlertCreateDto.  # noqa: E501
        :type: int
        """

        self._ignore_until = ignore_until

    @property
    def message(self):
        """Gets the message of this AlertCreateDto.  # noqa: E501


        :return: The message of this AlertCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this AlertCreateDto.


        :param message: The message of this AlertCreateDto.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def number(self):
        """Gets the number of this AlertCreateDto.  # noqa: E501


        :return: The number of this AlertCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this AlertCreateDto.


        :param number: The number of this AlertCreateDto.  # noqa: E501
        :type: int
        """

        self._number = number

    @property
    def object_id(self):
        """Gets the object_id of this AlertCreateDto.  # noqa: E501


        :return: The object_id of this AlertCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._object_id

    @object_id.setter
    def object_id(self, object_id):
        """Sets the object_id of this AlertCreateDto.


        :param object_id: The object_id of this AlertCreateDto.  # noqa: E501
        :type: int
        """

        self._object_id = object_id

    @property
    def origin(self):
        """Gets the origin of this AlertCreateDto.  # noqa: E501


        :return: The origin of this AlertCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._origin

    @origin.setter
    def origin(self, origin):
        """Sets the origin of this AlertCreateDto.


        :param origin: The origin of this AlertCreateDto.  # noqa: E501
        :type: str
        """
        allowed_values = ["system", "trap", "flow"]  # noqa: E501
        if origin not in allowed_values:
            raise ValueError(
                "Invalid value for `origin` ({0}), must be one of {1}"  # noqa: E501
                .format(origin, allowed_values)
            )

        self._origin = origin

    @property
    def plugin_name(self):
        """Gets the plugin_name of this AlertCreateDto.  # noqa: E501


        :return: The plugin_name of this AlertCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._plugin_name

    @plugin_name.setter
    def plugin_name(self, plugin_name):
        """Sets the plugin_name of this AlertCreateDto.


        :param plugin_name: The plugin_name of this AlertCreateDto.  # noqa: E501
        :type: str
        """

        self._plugin_name = plugin_name

    @property
    def poll_id(self):
        """Gets the poll_id of this AlertCreateDto.  # noqa: E501


        :return: The poll_id of this AlertCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._poll_id

    @poll_id.setter
    def poll_id(self, poll_id):
        """Sets the poll_id of this AlertCreateDto.


        :param poll_id: The poll_id of this AlertCreateDto.  # noqa: E501
        :type: int
        """

        self._poll_id = poll_id

    @property
    def severity(self):
        """Gets the severity of this AlertCreateDto.  # noqa: E501


        :return: The severity of this AlertCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._severity

    @severity.setter
    def severity(self, severity):
        """Sets the severity of this AlertCreateDto.


        :param severity: The severity of this AlertCreateDto.  # noqa: E501
        :type: int
        """

        self._severity = severity

    @property
    def start_time(self):
        """Gets the start_time of this AlertCreateDto.  # noqa: E501

        Unix timestamp with milliseconds proximity  # noqa: E501

        :return: The start_time of this AlertCreateDto.  # noqa: E501
        :rtype: int
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this AlertCreateDto.

        Unix timestamp with milliseconds proximity  # noqa: E501

        :param start_time: The start_time of this AlertCreateDto.  # noqa: E501
        :type: int
        """

        self._start_time = start_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AlertCreateDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AlertCreateDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
